name: Generate ASCII Artwork
on:
  workflow_dispatch:
   inputs:
    loglevel:
      description: "Log level"
      requested: true
      default: 'warning'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        env:
          stepVar1: stepvalue1
        run: |
          echo "The value for stepvar1: $stepVar1"
