name: My First workflow
on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      -name: welcome message
       run: cat hello.sh
      -name: List files
       run: ls
      -name: Read file
       run: cat README.md